name: Build documentation

on:
  pull_request:
    branches: [main]
  workflow_call:
  workflow_dispatch:

env:
  DEB_PYTHON_INSTALL_LAYOUT: deb_system
  DISPLAY: ":99.0"
  CI: 1

jobs:

  build-main:
    runs-on: ubuntu-24.04
    container: ghcr.io/fenics/dolfinx/lab:stable
    env:
      PUBLISH_DIR: ./_build
      PYVISTA_OFF_SCREEN: false
      PYVISTA_JUPYTER_BACKEND: "html"

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          python3 -m pip install ".[docs]"

      - name: Build docs
        run: python3 -m sphinx -b html . ${{ env.PUBLISH_DIR }}

  build-versions:
    needs: build-main
    runs-on: ubuntu-24.04
    container: ghcr.io/fenics/dolfinx/lab:stable
    env:
      PUBLISH_DIR: ./_build
      PYVISTA_OFF_SCREEN: false
      PYVISTA_JUPYTER_BACKEND: "html"

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          python3 -m pip install ".[docs]"

      - name: Build docs
        run: python3 -m sphinx -b html . ${{ env.PUBLISH_DIR }}

     

  upload:
    needs: build-main
    runs-on: ubuntu-24.04
    steps:
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ${{ env.PUBLISH_DIR }}